import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/banner";
import Card from "../components/Card/card";
import coffeeStores from "../data/coffee-stores.json";

export async function getStaticProps(context) {
  return {
    props: {
      coffeeStores,
    }, // will be passed to the page component as props
  };
}

export default function Home(props) {
  const buttonText = "View stores nearby";

  const handleOnBannerBtnClick = () => {
    console.log("banner btn");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={buttonText}
          handleOnClick={handleOnBannerBtnClick}
        />
        {coffeeStores.length > 0 && (
          <>
            <h2 className={styles.heading2}>Berlin Coffee Shops</h2>
            <div className={styles.cardLayout}>
              {coffeeStores.map((coffeeStore) => {
                return (
                  <Card
                    name={coffeeStore.name}
                    href={`/coffee-store/${coffeeStore.id}`}
                    imgUrl={coffeeStore.imgUrl}
                    className={styles.card}
                    key={coffeeStore.id}
                  />
                );
              })}
            </div>
          </>
        )}
      </main>
    </div>
  );
}
