import Head from "next/head";
import styles from "../styles/Home.module.css";
import Banner from "../components/Banner/banner";
import Card from "../components/Card/card";

export default function Home() {
  const buttonText = "View stores nearby";

  const handleOnBannerBtnClick = () => {
    console.log("banner btn");
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Shops</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText={buttonText}
          handleOnClick={handleOnBannerBtnClick}
        />
        <div className={styles.cardLayout}>
          <Card name="Dark coffee" href="/" image="" className={styles.card} />
        </div>
      </main>
    </div>
  );
}
